name: HTMLCheck

on:
  push:
    branches: ["main"]

jobs:
  TestHtml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check HTML Syntax
        run: npx prettier *.html
